collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.1942356
  brandStrength: 0.9931078
  lightness: 0.622807
  brandColors:
    - '#BF9FA0'
    - '#DAB7B7'
    - '#967878'
    - '#603A30'
    - '#7C544D'
  rhythmicContrast: 0.6798246
layout_spectrum: 0.6328321
name: Stephen Bauman Artworks
