collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.622807
  brandColors:
    - '#3A3A3A'
    - '#F0F6F8'
    - '#28609F'
    - '#67A8D4'
    - '#050408'
  rhythmicContrast: 1
typography_spectrum: 1
layout_spectrum: 0.7005013
name: Stephen Bauman Artworks
