collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.1942356
  brandStrength: 0.9931078
  lightness: 0.622807
  brandColors:
    - '#034D4C'
    - '#2CB3B7'
    - '#3C8080'
    - '#FE77AF'
    - '#978B9B'
  rhythmicContrast: 0.6798246
layout_spectrum: 0.7005013
name: Stephen Bauman Artworks
