collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.932933
  brandStrength: 0.3765664
  lightness: 0.3182957
  brandColors:
    - '#746967'
    - '#9F7C01'
    - '#161421'
    - '#3F3F57'
    - '#AE8F86'
  rhythmicContrast: 0.5469925
layout_spectrum: 0.2988722
name: Stephen Bauman Artworks
