collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.932933
  brandStrength: 0.5031328
  rhythmicContrast: 0.5469925
  brandColors:
    - '#131017'
    - '#3C3A48'
    - '#4E5F73'
    - '#6F798C'
    - '#C0A170'
  lightness: 0.3182957
typography_spectrum: 1
layout_spectrum: 0.03634085
name: Stephen Bauman Artworks
